version: "3.8"
services:
  db:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: virtual_trainer_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "6500:5432"
volumes:
  db_data:
